import 'package:dto/dto.dart';
import 'package:firestore_odm/firestore_odm.dart';

final List<JournalEntry> entries = [
  JournalEntry(
    id: FirestoreODM.autoGeneratedId,
    title: 'First day of summer',
    content: 'Today was the first day of summer. The sun was shining and I felt so happy.',
    userId: '',
    createdAt: DateTime(2026, 6, 15, 9, 0),
  ),
  JournalEntry(
    id: FirestoreODM.autoGeneratedId,
    title: 'Football game!',
    content: 'Watched the football game with friends. What an amazing match!',
    userId: '',
    createdAt: DateTime(2026, 7, 2, 20, 35),
  ),
  JournalEntry(
    id: FirestoreODM.autoGeneratedId,
    title: 'A weird day...',
    content: 'Everything felt strange today. Hard to explain but I needed to write it down.',
    userId: '',
    createdAt: DateTime(2026, 6, 27, 18, 35),
  ),
];