import 'package:dto/dto.dart';
import 'package:firestore_odm/firestore_odm.dart';

final List<AppUser> users = [
  AppUser(
    id: FirestoreODM.autoGeneratedId,
    firstName: 'Marwa',
    lastName: 'Haddaji',
    email: 'marwa@example.com',
    currentStreak: 3,
    longestStreak: 7,
  ),
  AppUser(
    id: FirestoreODM.autoGeneratedId,
    firstName: 'Yuna',
    lastName: 'Mizaki',
    email: 'yuna@example.com',
    currentStreak: 1,
    longestStreak: 5,
  ),
  AppUser(
    id: FirestoreODM.autoGeneratedId,
    firstName: 'Elisa',
    lastName: 'Jaswal',
    email: 'elisa@example.com',
    currentStreak: 7,
    longestStreak: 7,
    unlockedBadges: ['first_bloom', 'week_streak'],
  ),
];